Add about and collectibles types
5afe/safe-client-gateway pull request #931
Opened 2022-07-22 12:38 UTC by moisses89

Closes #928

2022-07-22 12:39 UTC, moisses89 commented on src/routes/about/routes.rs
> +    Ok(Json(client.get(request).await?.body))
This should return Json<BackBoneType>

2022-07-22 12:53 UTC, moisses89 commented
@fmrsabino regarding this fragment of code:
```
CacheResponse::new(&context, ChainCache::from(chain_id.as_str()))
        .duration(about_cache_duration())
        .resp_generator(|| handlers::get_master_copies(&context, chain_id.as_str()))
        .execute()
        .await
```
CacheResponse->execute returns `ApiResult<RawJson<String>>>` 
Instead rewrite execute I would like to add a method that returns from cache the result in String and in each endpoint cast the result to `ApiResult<Json<CorrespondingType>>>`
What do you think about this way to do this?

2022-07-22 13:14 UTC, fmrsabino commented
> @fmrsabino regarding this fragment of code:
> 
> ```
> CacheResponse::new(&context, ChainCache::from(chain_id.as_str()))
>         .duration(about_cache_duration())
>         .resp_generator(|| handlers::get_master_copies(&context, chain_id.as_str()))
>         .execute()
>         .await
> ```
> 
> CacheResponse->execute returns `ApiResult<RawJson<String>>>` Instead rewrite execute I would like to add a method that returns from cache the result in String and in each endpoint cast the result to `ApiResult<Json<CorrespondingType>>>` What do you think about this way to do this?

Instead of casting I'd probably have it as a Generic output. This might be a bigger change however so you can also try parsing the `String` to a specific type using `serde` (altough this might result in unecessary serializations when we return from the route:  `String` -> `T` -> `U`)

2022-07-22 13:16 UTC, fmrsabino commented
> Closes #928

This PR shouldn't close this issue. The issue is more about having it on all endpoint and this is specific to the About the Collectibles

2022-07-29 13:35 UTC, rmeissner requested changes

2022-07-29 13:35 UTC, rmeissner commented on src/routes/collectibles/handlers.rs
> +    Ok(Json(serde_json::from_str::<Vec<ServiceCollectible>>(
This doesn't make any sense. We first serialize them as a string and then convert them back to structs to convert them back to strings. 

With our current caching we cannot use the `Json` type.

2022-07-29 13:36 UTC, rmeissner commented on src/routes/collectibles/handlers.rs
> +    Ok(Json(serde_json::from_str::<Vec<ServiceCollectible>>(
Just to provider better documentation I would not add this additional parsing overhead

2023-01-18 10:12 UTC, fmrsabino commented
We are targeting this work in https://github.com/5afe/safe-client-gateway-nest

2023-01-18 10:12 UTC, closed without merging